---
- name: "php cli installed"
  sudo: yes
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: php_cli_packages
  when: item.name is defined

- include: "phpini.yml"
- include: "opcache.yml"
